version: "3.7"
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: monorepo
      MONGO_INITDB_ROOT_PASSWORD: monorepo
    ports:
      - "27017:27017"
